# Generated by Django 5.2.7 on 2025-11-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=42332443, max_length=100),
            preserve_default=False,
        ),
    ]
